---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocab-backend
  labels:
    app: vocab
    tier: backend
spec:
  selector:
    matchLabels:
      app: vocab
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: vocab
        tier: backend
    spec:
      containers:
        - name: vocab
          image: "ruedigermueller/vocab_backend"
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vocab-secret
                  key: jwt_secret
            - name: TYPEORM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vocab-secret
                  key: db_user
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vocab-secret
                  key: db_password
            - name: TYPEORM_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: dbconnection
                  key: db_connection_type
            - name: TYPEORM_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: dbconnection
                  key: db_name              
            - name: TYPEORM_ENTITIES
              valueFrom:
                configMapKeyRef:
                  name: dbconnection
                  key: db_entities    
            - name: TYPEORM_HOST
              valueFrom:
                configMapKeyRef:
                  name: dbconnection
                  key: db_host    
            - name: TYPEORM_MIGRATIONS
              valueFrom:
                configMapKeyRef:
                  name: dbconnection
                  key: db_migrations    
            - name: TYPEORM_PORT
              valueFrom:
                configMapKeyRef:
                  name: dbconnection
                  key: db_port       
            - name: TYPEORM_SYNCHRONIZE
              valueFrom:
                configMapKeyRef:
                  name: dbconnection
                  key: db_synchronize
            # Uncomment in case you want to connect to DB on Heroku
            # - name: TYPEORM_DRIVER_EXTRA
            #  value: "{\"ssl\":{\"rejectUnauthorized\":false}}"