apiVersion: v1
kind: Service
metadata:
  name: vocab-backend
spec:
  selector:
    app: vocab
    tier: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocab-backend
spec:
  selector:
    matchLabels:
      app: vocab
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: vocab
        tier: backend
    spec:
      containers:
        - name: vocab
          image: "ruedigermueller/vocab_backend"
          ports:
            - name: http
              containerPort: 3000