---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocab-db
  labels:
    app: vocab
    tier: db
spec:
  selector:
    matchLabels:
      app: vocab
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vocab
        tier: db
    spec:
      containers:
      - image: postgres
        name: postgres-db
        env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vocab-secret
                  key: db_password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: vocab-secret
                  key: db_user
            - name: POSTGRES_DB
              value: d2qc8kts4lremi
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: postgres-disk
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-disk
        persistentVolumeClaim:
          claimName: postgres-pv-claim