name: Build and deploy for manual test

on:
  push:
    branches:
      - master

jobs: 
  build_and_push_docker_image:
    uses: RuedigerMueller/GitHubWorkflows/.github/workflows/build_and_optionally_push.yml@main
    with:
      DOCKERHUB_USERNAME: ruedigermueller
      DOCKERHUB_REPOSITORY: vocab_backend
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  deploy_to_heroku_for_manual_test:
    needs: [build_and_push_docker_image]
    uses: RuedigerMueller/GitHubWorkflows/.github/workflows/deploy_to_heroku.yml@main
    with:
      DOCKERHUB_USERNAME: ruedigermueller
      DOCKERHUB_REPOSITORY: vocab_backend
      HEROKU_REPOSITORY: vocabbetest
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}