name: Backend build and test pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: npm install
        env:
          CI: true
      - name: Test
        run: npm test
        env:
          CI: true
